### ISSUE TITLE
Loading constructors / Something got wrong/1

### ISSUE THREAD

**Issue by ZainaliSyed** [smartzplatform/smartz#16]
@patsak @quantum13 @mxpaul @BoogerWooger 

- I have run these Commands mention below , Build is also Successful but i alway get an **Loading constructors** on my http://localhost:3000/

- I have also tried upload  contracts **http://localhost:3000/ctor-add**  , I alway get an Error : 
    **Something got wrong/1** 

# run server
docker-compose build
docker-compose up

# migrations
docker exec -it smartz_backend /bin/sh
source .venv/bin/activate
python3 manage.py migrate

![loader error](https://user-images.githubusercontent.com/24393023/43149731-a8e88084-8f81-11e8-9e9d-99271b811c64.png)
![something got wrong 1](https://user-images.githubusercontent.com/24393023/43149732-a90f7e8c-8f81-11e8-928e-b7d8bc6b9cf3.png)

**Comment by quantum13** [comment]
Hi, we haven't thought that somebody would run smartz so soon :)
Smartz depends on two microservices which sources we will open in few days

**Comment by ZainaliSyed** [comment]
@quantum13  Please Fix it  ASP or please guide any other alternative for that .

**Comment by quantum13** [comment]
Hi, we've just opened sources of two microservices:
https://github.com/smartzplatform/constructor_call_service
https://github.com/smartzplatform/eos_compilation_service

see its readme to run and updated readme of smartz

**Comment by ZainaliSyed** [comment]
@quantum13 
Please Guide Whenever `pipenv run python3 wsgi_app.py` for (Constructor call service) [https://github.com/smartzplatform/constructor_call_service] I alway got Error 

  File "wsgi_app.py", line 33, in <module>
    from smartz.json_schema import load_schema, is_conforms2schema_part
ModuleNotFoundError: No module named 'smartz'

### As Guided I have Change my URL as well
backend/smartzcore/settings.py Folder :

```
 SMARTZ_CONSTRUCTOR_CALL_SERVICE_URL = os.environ.get(
            'http://service.host:port/call')
    assert SMARTZ_CONSTRUCTOR_CALL_SERVICE_URL, "Constructor call service url is not set in env"

   SMARTZ_EOS_COMPILATION_SERVICE_URL = os.environ.get(
            'http://service.host:port/compile')
    assert SMARTZ_EOS_COMPILATION_SERVICE_URL, "Eos compilation service url is not set in env"
```

**Comment by Suneel-RoR** [comment]
I am stuck on same issue unable to process with complete installation of smartz.io.  

@quantum13 , your help would be appreciated

**Comment by quantum13** [comment]
Have you populated `.env` with SMARTZ_REPO_PATH?
https://github.com/smartzplatform/constructor_call_service#installation

**Comment by ZainaliSyed** [comment]
@quantum13  Your Solution works to start `Constructor call service` on port **`5000` PORT** 

**Unfortunately** i am still getting Loading Constructor Issue , Please guide me 

![screen shot 2018-08-08 at 11 03 08 pm](https://user-images.githubusercontent.com/24393023/43856701-b676b8c8-9b62-11e8-8406-ef20508ba7ff.png)

**Comment by quantum13** [comment]
Why have you changed this?
>As Guided I have Change my URL as well
>backend/smartzcore/settings.py Folder :

Please, read insctuctions: https://github.com/smartzplatform/smartz#running-local-server

**Comment by ZainaliSyed** [comment]
@quantum13  Thank you i have revert my changes both micro services have been started as well,
  but still **`i am stuck`** , I am able to understand what thing i am missing . 

   _I have read all those instruction as well there is no error this time but still **Constructor loading** is showing_ 

```
 SMARTZ_CONSTRUCTOR_CALL_SERVICE_URL = os.environ.get(
        'CONSTRUCTOR_CALL_SERVICE_URL')

 SMARTZ_EOS_COMPILATION_SERVICE_URL = os.environ.get(
        'EOS_COMPILATION_SERVICE_URL')

```

**Comment by quantum13** [comment]
Have you successfuly uploaded constructor?

**Comment by ZainaliSyed** [comment]
@quantum13  Unfortunately it's working yet . Still getting  **Constructor loading**

**Comment by quantum13** [comment]
What exactly doesn't work?

**Comment by quantum13** [comment]
@ZainaliSyed Where you are getting this message?

**Comment by ZainaliSyed** [comment]
@quantum13 

On Main Page **`http://localhost:3000/`** and I am not able to upload contract as well  **`http://localhost:3000/ctor-add`**


![screen shot 2018-08-10 at 7 10 33 pm](https://user-images.githubusercontent.com/24393023/43962605-9adf6f22-9cd1-11e8-9f7a-603b4eb05222.png)

**Comment by quantum13** [comment]
> I am not able to upload contract as well
What happened during upload?

>On Main Page
Its normal behavioue without constructors

**Comment by ZainaliSyed** [comment]
This is what i am getting return 

![screen shot 2018-08-10 at 7 46 57 pm](https://user-images.githubusercontent.com/24393023/43964444-4f2ccf98-9cd6-11e8-969d-abbd44fcc9a0.png)

**Comment by quantum13** [comment]
You should update repository to actial master and should try constructors from https://github.com/smartzplatform/SDK

**Comment by ZainaliSyed** [comment]
Steps to produce : 

1. Done git clone  https://github.com/smartzplatform/SDK
2. Upload SDK/constructor_examples/ledger_constructor.py file on my Localhost
3. Got same Error on **http://localhost:3000/ctor-add** (Something got wrong/1)

**Comment by quantum13** [comment]
Please check docker logs (smartz backend) and upload a piece of log with errors

**Comment by ZainaliSyed** [comment]
I am getting this logs , Please guide what to do 


```
backend_1   | Failed to call constructor method get_version: HTTPConnectionPool(host='constructor_call_service.dev', port=80): Max retries exceeded with url: /call (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88f03387b8>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
backend_1   | 2018-08-10 15:46:59,148 [ERROR][utils.responses] Error response: Something got wrong/1
backend_1   | [pid: 10|app: 0|req: 12/12] 172.18.0.1 () {50 vars in 1438 bytes} [Fri Aug 10 15:46:58 2018] POST /api/constructors/upload => generated 34 bytes in 437 msecs (HTTP/1.1 200) 3 headers in 141 bytes (1 switches on core 0)
frontend_1  | 172.18.0.1 - - [10/Aug/2018:15:46:59 +0000] "POST /api/constructors/upload HTTP/1.1" 200 65 "http://localhost:3000/ctor-add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
```

**Comment by quantum13** [comment]
You haven't changed services urls as descried at # change url of services in smartzplatform.env

Please, join our community at telegram https://t.me/smartz_en and ask questions there. It will faster

**Comment by ZainaliSyed** [comment]
@quantum13 Sorry to disturb but telegram is resisted in our region therefore can not communicate there.  I have update smartplateform.env file like: 
```
ENVIRONMENT=dev

CONSTRUCTOR_CALL_SERVICE_URL=http://localhost:5000/call
EOS_COMPILATION_SERVICE_URL=http://localhost:5001/compile

DJANGO_SECRET_KEY=abc123

# application db settings
DB_HOST=postgres
DB_USER=smartz
DB_PASS=changeme_gu5Wi
DB_NAME=smartz
# developer postgres container settings (should be the same)
POSTGRES_USER=smartz
POSTGRES_PASSWORD=changeme_gu5Wi
POSTGRES_DB=smartz` 
```

but getting below error while upload new contract: 

```
backend_1   | Failed to call constructor method get_version: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /call (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd419970080>: Failed to establish a new connection: [Errno 111] Connection refused',))
backend_1   | 2018-08-10 16:46:46,969 [ERROR][utils.responses] Error response: Something got wrong/1
frontend_1  | 172.18.0.1 - - [10/Aug/2018:16:46:46 +0000] "POST /api/constructors/upload HTTP/1.1" 200 65 "http://localhost:3000/ctor-add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
backend_1   | [pid: 10|app: 0|req: 2/2] 172.18.0.1 () {50 vars in 1438 bytes} [Fri Aug 10 16:46:46 2018] POST /api/constructors/upload => generated 34 bytes in 72 msecs (HTTP/1.1 200) 3 headers in 141 bytes (1 switches on core 0)

```

It would be much appreciated your help for final touch to setup application on our development machine.  Though you helped throughout installation process.

**Comment by quantum13** [comment]
You cannot use localhost, since this app running in docker container
In instruction written to use external ip address (not localhost or 127.0.0.1)

**Comment by ZainaliSyed** [comment]
@quantum13  You are right i am getting HTML sort of ERROR I have attach error in file you have look . Please give sample contract if you have so i can upload that .
 
[Construtor file.txt](https://github.com/smartzplatform/smartz/files/2278851/Construtor.file.txt)

**Comment by quantum13** [comment]
Some trubles with docker:
docker: Error response from daemon: Mounts denied:

Constructor call service runs docker containers to run constructors in in.
In your case this service can't do it
